# These values should be set from `corset debug -s zkevm.bin`
[spillings]
ADD = 1
BIN = 15
BLAKE_MODEXP_DATA = 1
BLOCK_DATA = 6
BLOCK_HASH = 1
EC_DATA = 11
EUC = 1
EXP = 5
EXT = 7
GAS = 1
HUB = 12
LOG_DATA = 1
LOG_INFO = 5
MMIO = 0
MMU = 10
MOD = 7
MUL = 8
MXP = 3
OOB = 5
RLP_ADDR = 7
RLP_TXN = 7
RLP_TXN_RCPT = 7
ROM = 1
ROM_LEX = 1
SHAKIRA_DATA = 1
SHF = 15
STP = 4
TRM = 7
TXN_DATA = 8
WCP = 15

BIN_REFERENCE_TABLE = 0
SHF_REFERENCE_TABLE = 0
INSTRUCTION_DECODER = 0

PRECOMPILE_ECRECOVER_EFFECTIVE_CALL = 0
PRECOMPILE_SHA2_BLOCKS      = 0
PRECOMPILE_RIPEMD_BLOCKS    = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALL    = 0
PRECOMPILE_ECADD_EFFECTIVE_CALL     = 0
PRECOMPILE_ECMUL_EFFECTIVE_CALL     = 0
PRECOMPILE_ECPAIRING_EFFECTIVE_CALL = 0
PRECOMPILE_ECPAIRING_MILLER_LOOP = 0
PRECOMPILE_BLAKE_ROUNDS   = 0
PRECOMPILE_BLAKE_EFFECTIVE_CALL   = 0

# PRECOMPILE_SHA2_EFFECTIVE_CALL   = ?
# PRECOMPILE_RIPEMD_EFFECTIVE_CALL = ?

BLOCK_KECCAK      = 0
BLOCK_L1_SIZE     = 0
BLOCK_L2_L1_LOGS  = 0
BLOCK_TRANSACTION = 0
