# Extends the mainnet preset
PRESET_BASE: 'mainnet'
CONFIG_NAME: testnet # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis

# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
# Mar-01-2021 08:53:32 AM +UTC
# This is an invalid valid and should be updated when you create the genesis
MIN_GENESIS_TIME: $GENESIS_TIME
GENESIS_FORK_VERSION: 0x10000038
GENESIS_DELAY: 10

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x20000038
ALTAIR_FORK_EPOCH: 0
# Merge
BELLATRIX_FORK_VERSION: 0x30000038
BELLATRIX_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Capella
CAPELLA_FORK_VERSION: 0x40000038
CAPELLA_FORK_EPOCH: 0

# DENEB
DENEB_FORK_VERSION: 0x50000038
DENEB_FORK_EPOCH: 0

# ELECTRA
ELECTRA_FORK_VERSION: 0x60000038
ELECTRA_FORK_EPOCH: 0

# FULU
FULU_FORK_VERSION: 0x70000038
FULU_FORK_EPOCH: 0

# GLOAS
GLOAS_FORK_VERSION: 0x80000038
GLOAS_FORK_EPOCH: 18446744073709551615

# FUTURE
EIP7805_FORK_VERSION=: 0x90000038
EIP7805_FORK_EPOCH: 18446744073709551615

# FUTURE
EIP7441_FORK_VERSION=: 0xa0000038
EIP7441_FORK_EPOCH: 18446744073709551615


# Time parameters
# ---------------------------------------------------------------
# 12 seconds (*deprecated*)
SECONDS_PER_SLOT: 1
# 1000 milliseconds
SLOT_DURATION_MS: 1000
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 1
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 3
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 16

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 32

# Deneb
# 2**3 (= 8) (*deprecated*)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8

# Electra
# 2**6 * 10**9 (= 64,000,000,000) Gwei
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 64000000000
# 2**7 * 10**9 (= 256,000,000,000) Gwei
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: 128000000000

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40
# 20%
REORG_HEAD_WEIGHT_THRESHOLD: 20
# 160%
REORG_PARENT_WEIGHT_THRESHOLD: 160
# `2` epochs
REORG_MAX_EPOCHS_SINCE_FINALIZATION: 2

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 31648428
DEPOSIT_NETWORK_ID: 31648428
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Networking
# ---------------------------------------------------------------
# `10 * 2**20` (= 10485760, 10 MiB)
MAX_PAYLOAD_SIZE: 10485760
# 2**10 (= 1,024) blocks
MAX_REQUEST_BLOCKS: 1024
# 2**8 (= 256) epochs
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
# MIN_VALIDATOR_WITHDRAWABILITY_DELAY + CHURN_LIMIT_QUOTIENT // 2 (= 33,024) epochs
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 272
# `10 * 2**20` (=10485760, 10 MiB)
MAX_CHUNK_SIZE: 10485760
# 5s
TTFB_TIMEOUT: 5
# 10s
RESP_TIMEOUT: 10
# 2**5 (= 32) slots

ATTESTATION_PROPAGATION_SLOT_RANGE: 32
# 500ms
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
# 2 subnets per node
SUBNETS_PER_NODE: 2
# 2**6 (= 64) subnets
ATTESTATION_SUBNET_COUNT: 64
# 0 bits
ATTESTATION_SUBNET_EXTRA_BITS: 0
# ceillog2(ATTESTATION_SUBNET_COUNT) + ATTESTATION_SUBNET_EXTRA_BITS (= 6 + 0) bits
ATTESTATION_SUBNET_PREFIX_BITS: 6

# 6 blobs
MAX_BLOBS_PER_BLOCK: 6

# Deneb
# 2**7 (= 128) blocks
MAX_REQUEST_BLOCKS_DENEB: 128

# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK (= 128 * 6) sidecars
MAX_REQUEST_BLOB_SIDECARS: 768

# 2**12 (= 4,096) epochs
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
# 6 subnets
BLOB_SIDECAR_SUBNET_COUNT: 6



# Electra
# 9 subnets
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: 9
# 9 blobs
MAX_BLOBS_PER_BLOCK_ELECTRA: 9
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK_ELECTRA
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: 1152

# Fulu
# 2**7 (= 128) groups
FULU_MAX_BLOBS_PER_TX: 6

# 2**7 (= 128) groups
NUMBER_OF_CUSTODY_GROUPS: 128
# 2**7 (= 128) subnets
DATA_COLUMN_SIDECAR_SUBNET_COUNT: 128
# MAX_REQUEST_BLOCKS_DENEB * NUMBER_OF_COLUMNS (= 128 * 128) sidecars
MAX_REQUEST_DATA_COLUMN_SIDECARS: 16384
# 2**3 (= 8) samples
SAMPLES_PER_SLOT: 8
# 2**2 (= 4) sidecars
CUSTODY_REQUIREMENT: 4
# 2**3 (= 8) sidecars
VALIDATOR_CUSTODY_REQUIREMENT: 8
# 2**5 * 10**9 (= 32,000,000,000) Gwei
BALANCE_PER_ADDITIONAL_CUSTODY_GROUP: 32000000000
# 2**12 (= 4,096) epochs
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: 4096

# Blob Scheduling
# ---------------------------------------------------------------

BLOB_SCHEDULE: []
BPO_1_EPOCH: 18446744073709551615
BPO_1_MAX_BLOBS: 9
BPO_1_TARGET_BLOBS: 6
BPO_1_BASE_FEE_UPDATE_FRACTION: 0

BPO_2_EPOCH: 18446744073709551615
BPO_2_MAX_BLOBS: 9
BPO_2_TARGET_BLOBS: 6
BPO_2_BASE_FEE_UPDATE_FRACTION: 0

BPO_3_EPOCH: 18446744073709551615
BPO_3_MAX_BLOBS: 9
BPO_3_TARGET_BLOBS: 6
BPO_3_BASE_FEE_UPDATE_FRACTION: 0

BPO_4_EPOCH: 18446744073709551615
BPO_4_MAX_BLOBS: 9
BPO_4_TARGET_BLOBS: 6
BPO_4_BASE_FEE_UPDATE_FRACTION: 0

BPO_5_EPOCH: 18446744073709551615
BPO_5_MAX_BLOBS: 9
BPO_5_TARGET_BLOBS: 6
BPO_5_BASE_FEE_UPDATE_FRACTION: 0

# For Gloas onwards

ATTESTATION_DUE_BPS_GLOAS: 2500
AGGREGATE_DUE_BPS_GLOAS: 5000
SYNC_MESSAGE_DUE_BPS_GLOAS: 2500
CONTRIBUTION_DUE_BPS_GLOAS: 5000

VIEW_FREEZE_CUTOFF_BPS: 7500
INCLUSION_LIST_SUBMISSION_DUE_BPS: 6667
PROPOSER_INCLUSION_LIST_CUTOFF_BPS: 9167