input_traces_directory = "/data/traces/raw"
output_traces_directory = "/data/traces/v1/conflated"
traces_api_version = "0.2.0"
traces_file_extension = "json.gz"

[api]
port = 8080
path = "/"
# if =0, it will create one verticle per core (or hyperthread if supported)
number_of_verticles = 2
observability_port = 8090
