environment = "devnet"
version = "6.1.3"                              # TODO @gbotrel hunt all version definitions.
assets_dir = "./prover-assets"
log_level = 4                                  # TODO @gbotrel will be refactored with new logger.

[controller]
retry_delays = [0, 1]
enable_execution = false 
enable_blob_decompression = false
enable_aggregation = false
spot_instance_reclaim_time_seconds = 120
termination_grace_period_seconds = 1800

[controller.limitless_jobs]
enable_bootstrapper   = false 
enable_conglomerator = false
enable_gl = true  
gl_mods =  ["ARITH-OPS", "BLS_G1", "BLS_G2", "BLS_KZG", "BLS_PAIR", "ECDSA", "ECPAIRING", "ELLIPTIC_CURVES", "G2_CHECK", "HUB-KECCAK", "MODEXP_256", "MODEXP_LARGE", "P256", "SHA2", "STATIC", "TINY-STUFFS"]
enable_lpp = true
lpp_mods =  ["ARITH-OPS", "BLS_G1", "BLS_G2", "BLS_KZG", "BLS_PAIR", "ECDSA", "ECPAIRING", "ELLIPTIC_CURVES", "G2_CHECK", "HUB-KECCAK", "MODEXP_256", "MODEXP_LARGE", "P256", "SHA2", "STATIC", "TINY-STUFFS"]


[execution]
prover_mode = "limitless"
conflated_traces_dir = "/home/ubuntu/test_devnet/traces/conflated"
requests_root_dir = "/home/ubuntu/test_devnet/prover-execution"
limitless_with_debug = false 
ignore_compatibility_check = true

[exec_limitless]
metadata_dir = "/tmp/exec-limitless/metadata"
witness_dir = "/tmp/exec-limitless/witness"
subproofs_dir = "/tmp/exec-limitless/subproofs"
shared_rnd_dir = "/tmp/exec-limitless/commit"
shared_failure_dir = "/tmp/exec-limitless/failure"
timeout_seconds = 2100 

[blob_decompression]
prover_mode = "full"
requests_root_dir = "/home/ubuntu/mainnet-test-2/v2/compression"
dict_paths = ["lib/compressor/compressor_dict.bin", "lib/compressor/dict/25-04-21.bin"]

[aggregation]
prover_mode = "full"
requests_root_dir = "/home/ubuntu/mainnet-test-2/v2/aggregation"
num_proofs = [10, 20, 50, 100, 200, 400]
allowed_inputs = ["execution", "execution-large", "execution-limitless", "blob-decompression-v0", "blob-decompression-v1"]
verifier_id = 1

[public_input_interconnection]
max_nb_decompression = 400
max_nb_execution = 400
max_nb_circuits = 400
execution_max_nb_msg = 16
l2_msg_merkle_depth = 5
l2_msg_max_nb_merkle = 200

[layer2]
chain_id = 59139
message_service_contract = "0x33bf916373159a8c1b54b025202517bfdbb7863d"

[traces_limits]
ADD = 262144
BIN = 262144
BLAKE_MODEXP_DATA = 16384
BLOCK_DATA = 4096
BLOCK_HASH = 4096
EC_DATA = 65536
EUC = 65536
EXP = 65536
EXT = 524288
GAS = 65536
HUB = 2097152
LOG_DATA = 65536
LOG_INFO = 4096
MMIO = 2097152
MMU = 1048576
MOD = 131072
MUL = 65536
MXP = 524288
OOB = 262144
RLP_ADDR = 4096
RLP_TXN = 131072
RLP_TXN_RCPT = 65536
ROM = 8388608
ROM_LEX = 1024
SHAKIRA_DATA = 65536
SHF = 262144
STP = 16384
TRM = 32768
TXN_DATA = 8192
WCP = 262144
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS = 128
PRECOMPILE_SHA2_BLOCKS = 200
PRECOMPILE_RIPEMD_BLOCKS = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALLS = 32
PRECOMPILE_MODEXP_EFFECTIVE_CALLS_4096 = 1
PRECOMPILE_ECADD_EFFECTIVE_CALLS = 256
PRECOMPILE_ECMUL_EFFECTIVE_CALLS = 40
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS = 16
PRECOMPILE_ECPAIRING_MILLER_LOOPS = 64
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS = 64
PRECOMPILE_BLAKE_EFFECTIVE_CALLS = 0
PRECOMPILE_BLAKE_ROUNDS = 0
BLOCK_KECCAK = 8192
BLOCK_L1_SIZE = 1000000
BLOCK_L2_L1_LOGS = 16
BLOCK_TRANSACTIONS = 300
BIN_REFERENCE_TABLE = 262144
INSTRUCTION_DECODER = 512

BIT_SHL256 = 262144
BIT_SHL256_U7 = 262144
BIT_SHL256_U6 = 262144
BIT_SHL256_U5 = 262144
BIT_SHL256_U4 = 262144
BIT_SHL256_U3 = 262144
BIT_SHL256_U2 = 262144
BIT_SHL256_U1 = 262144
BIT_SHR256 = 262144
BIT_SHR256_U7 = 262144
BIT_SHR256_U6 = 262144
BIT_SHR256_U5 = 262144
BIT_SHR256_U4 = 262144
BIT_SHR256_U3 = 262144
BIT_SHR256_U2 = 262144
BIT_SHR256_U1 = 262144
BIT_SAR256 = 262144
BIT_SAR256_U7 = 262144
BIT_SAR256_U6 = 262144
BIT_SAR256_U5 = 262144
BIT_SAR256_U4 = 262144
BIT_SAR256_U3 = 262144
BIT_SAR256_U2 = 262144
BIT_SAR256_U1 = 262144
CALL_GAS_EXTRA = 262144
FILL_BYTES_BETWEEN = 262144
GAS_OUT_OF_POCKET = 262144
LOG2 = 262144
LOG2_U128 = 262144
LOG2_U64 = 262144
LOG2_U32 = 262144
LOG2_U16 = 262144
LOG2_U8 = 262144
LOG2_U4 = 262144
LOG2_U2 = 262144
LOG256 = 262144
LOG256_U128 = 262144
LOG256_U64 = 262144
LOG256_U32 = 262144
LOG256_U16 = 262144
MIN256_64 = 262144
SET_BYTE256 = 262144
SET_BYTE128 = 262144
SET_BYTE64 = 262144
SET_BYTE32 = 262144
SET_BYTE16 = 262144

U128 = 262144
U127 = 262144
U126 = 262144
U125 = 262144
U124 = 262144
U123 = 262144
U120 = 262144
U119 = 262144
U112 = 262144
U111 = 262144
U96 = 262144
U95 = 262144
U64 = 262144
U63 = 262144
U62 = 262144
U61 = 262144
U60 = 262144
U59 = 262144
U58 = 262144
U56 = 262144
U55 = 262144
U48 = 262144
U47 = 262144
U36 = 262144
U32 = 262144
U31 = 262144
U30 = 262144
U29 = 262144
U28 = 262144
U27 = 262144
U26 = 262144
U24 = 262144
U23 = 262144
U20 = 262144

PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS     = 1
PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS = 2
PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS               = 4
PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS               = 4
PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS           = 8
PRECOMPILE_BLS_FINAL_EXPONENTIATIONS                = 2
PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS         = 4
PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS        = 4
PRECOMPILE_BLS_C1_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS                  = 8

BLS_DATA                = 65536
RLP_UTILS               = 131072
POWER_REFERENCE_TABLE   = 32
BLS_REFERENCE_TABLE     = 512

# Start of new Osaka modules
PRECOMPILE_P256_VERIFY_EFFECTIVE_CALLS = 128

BIT_XOAN_U2   = 262144
BIT_XOAN_U4   = 262144
BIT_XOAN_U8   = 262144
BIT_XOAN_U16  = 262144
BIT_XOAN_U32  = 262144
BIT_XOAN_U64  = 262144
BIT_XOAN_U128 = 262144
BIT_XOAN_U256 = 262144
BYTE_16       = 262144
BYTE_32       = 262144
BYTE_64       = 262144
BYTE_128      = 262144
BYTE_256      = 262144
SIGNEXTEND    = 262144
MAX3_U128     = 262144
MAXLOG        = 262144
# End of new Osaka modules

[traces_limits_large]
ADD = 524288
BIN = 524288
BLAKE_MODEXP_DATA = 32768
BLOCK_DATA = 8192
BLOCK_HASH = 8192
EC_DATA = 131072
EUC = 131072
EXP = 131072
EXT = 1048576
GAS = 131072
HUB = 4194304
LOG_DATA = 131072
LOG_INFO = 8192
MMIO = 4194304
MMU = 2097152
MOD = 262144
MUL = 131072
MXP = 1048576
OOB = 524288
RLP_ADDR = 8192
RLP_TXN = 262144
RLP_TXN_RCPT = 131072
ROM = 8388608
ROM_LEX = 2048
SHAKIRA_DATA = 65536
SHF = 524288
STP = 32768
TRM = 65536
TXN_DATA = 16384
WCP = 524288
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS = 256
PRECOMPILE_SHA2_BLOCKS = 400
PRECOMPILE_RIPEMD_BLOCKS = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALLS = 64
PRECOMPILE_MODEXP_EFFECTIVE_CALLS_4096 = 1
PRECOMPILE_ECADD_EFFECTIVE_CALLS = 512
PRECOMPILE_ECMUL_EFFECTIVE_CALLS = 80
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS = 32
PRECOMPILE_ECPAIRING_MILLER_LOOPS = 128
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS = 128
PRECOMPILE_BLAKE_EFFECTIVE_CALLS = 0
PRECOMPILE_BLAKE_ROUNDS = 0
BLOCK_KECCAK = 8192
BLOCK_L1_SIZE = 1000000
BLOCK_L2_L1_LOGS = 16
BLOCK_TRANSACTIONS = 300
BIN_REFERENCE_TABLE = 262144
INSTRUCTION_DECODER = 512

BIT_SHL256 = 524288
BIT_SHL256_U7 = 524288
BIT_SHL256_U6 = 524288
BIT_SHL256_U5 = 524288
BIT_SHL256_U4 = 524288
BIT_SHL256_U3 = 524288
BIT_SHL256_U2 = 524288
BIT_SHL256_U1 = 524288
BIT_SHR256 = 524288
BIT_SHR256_U7 = 524288
BIT_SHR256_U6 = 524288
BIT_SHR256_U5 = 524288
BIT_SHR256_U4 = 524288
BIT_SHR256_U3 = 524288
BIT_SHR256_U2 = 524288
BIT_SHR256_U1 = 524288
BIT_SAR256 = 524288
BIT_SAR256_U7 = 524288
BIT_SAR256_U6 = 524288
BIT_SAR256_U5 = 524288
BIT_SAR256_U4 = 524288
BIT_SAR256_U3 = 524288
BIT_SAR256_U2 = 524288
BIT_SAR256_U1 = 524288
CALL_GAS_EXTRA = 524288
FILL_BYTES_BETWEEN = 524288
GAS_OUT_OF_POCKET = 524288
LOG2 = 524288
LOG2_U128 = 524288
LOG2_U64 = 524288
LOG2_U32 = 524288
LOG2_U16 = 524288
LOG2_U8 = 524288
LOG2_U4 = 524288
LOG2_U2 = 524288
LOG256 = 524288
LOG256_U128 = 524288
LOG256_U64 = 524288
LOG256_U32 = 524288
LOG256_U16 = 524288
MIN256_64 = 524288
SET_BYTE256 = 524288
SET_BYTE128 = 524288
SET_BYTE64 = 524288
SET_BYTE32 = 524288
SET_BYTE16 = 524288

U128 = 524288
U127 = 524288
U126 = 524288
U125 = 524288
U124 = 524288
U123 = 524288
U120 = 524288
U119 = 524288
U112 = 524288
U111 = 524288
U96 = 524288
U95 = 524288
U64 = 524288
U63 = 524288
U62 = 524288
U61 = 524288
U60 = 524288
U59 = 524288
U58 = 524288
U56 = 524288
U55 = 524288
U48 = 524288
U47 = 524288
U36 = 524288
U32 = 524288
U31 = 524288
U30 = 524288
U29 = 524288
U28 = 524288
U27 = 524288
U26 = 524288
U24 = 524288
U23 = 524288
U20 = 524288

PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS     = 2
PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS = 4
PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS               = 16
PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS               = 16
PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS           = 16
PRECOMPILE_BLS_FINAL_EXPONENTIATIONS                = 4
PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS         = 8
PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS        = 8
PRECOMPILE_BLS_C1_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS                  = 16

BLS_DATA                = 131072
RLP_UTILS               = 262144
POWER_REFERENCE_TABLE   = 32
BLS_REFERENCE_TABLE     = 512

# Start of new Osaka modules
PRECOMPILE_P256_VERIFY_EFFECTIVE_CALLS = 256

BIT_XOAN_U2   = 524288
BIT_XOAN_U4   = 524288
BIT_XOAN_U8   = 524288
BIT_XOAN_U16  = 524288
BIT_XOAN_U32  = 524288
BIT_XOAN_U64  = 524288
BIT_XOAN_U128 = 524288
BIT_XOAN_U256 = 524288
BYTE_16       = 524288
BYTE_32       = 524288
BYTE_64       = 524288
BYTE_128      = 524288
BYTE_256      = 524288
SIGNEXTEND    = 524288
MAX3_U128     = 524288
MAXLOG        = 524288
# End of new Osaka modules