# to use this file run
# docker compose -f compose-tracing-v2.yml -f compose-local-dev.overrides.yml --profile l2 --profile l1 up
volumes:
  testnet-data:
    name: "testnet-data"

services:
  sequencer:
    environment:
      TRACES_MIN_BLOCK_HEIGHT: 5000
      DATA_DIR: "/testnet-data/l2-sequencer-node/"
      NETRESTRICT: "${LINEA_TESTNET_ENODE_IP}"
      BOOTNODES: "${LINEA_TESTNET_ENODE}"
      ZKGETH_CLUSTER_SIZE: 2
      ZKGETH_CLUSTER_NODE_ID: 0
    entrypoint: ""
    command: [ "sh", "/scripts/node.sh", "59140", "/genesis.json", "0xa", "0x1C9C380" ]
    volumes:
      - ./geth/scripts:/scripts:ro
      - ./config/linea-testnet-genesis-PoA.json:/genesis.json:ro
      - ../tmp/testnet/:/data/
      - testnet-data:/testnet-data/

  traces-node:
    environment:
      TRACES_MIN_BLOCK_HEIGHT: 5000
      DATA_DIR: "/testnet-data/l2-zkgeth-traces-node/"
      NETRESTRICT: "${LINEA_TESTNET_ENODE_IP}"
      BOOTNODES: "${LINEA_TESTNET_ENODE}"
      ZKGETH_CLUSTER_SIZE: 2
      ZKGETH_CLUSTER_NODE_ID: 1
    entrypoint: ""
    command: [ "sh", "/scripts/node.sh", "59140", "/genesis.json", "0xa", "0x1C9C380" ]
    volumes:
      - ./geth/scripts:/scripts:ro
      - ./config/linea-testnet-genesis-PoA.json:/genesis.json:ro
      - ../tmp/testnet/:/data/
      - testnet-data:/testnet-data/

  traces-api:
#    image: consensys/linea-traces-api-facade:137ab52
#    command: [ 'echo', 'using local debugger' ]
    volumes:
      - ../tmp/testnet/:/data/

  prover:
#    image: consensys/linea-prover:8d1c974
    platform: linux/amd64
    volumes:
      - ../tmp/testnet/:/data/

  coordinator:
#    image: consensys/linea-coordinator:1d37365
    command: [ 'java', '-Dvertx.configurationFile=/var/lib/coordinator/vertx-options.json', '-Dlog4j2.configurationFile=/var/lib/coordinator/log4j2-dev.xml', '-jar', 'libs/coordinator.jar', '--traces-limits', 'config/traces-limits-v1.toml', '--smart-contract-errors', 'config/common/smart-contract-errors.toml', '--gas-price-cap-time-of-day-multipliers', 'config/gas-price-cap-time-of-day-multipliers.toml', 'config/coordinator-docker.config.toml', 'config/coordinator-docker-testnet.config.overrides.toml' ]
#    command: [ 'echo', 'using local debugger' ]
    volumes:
      - ../config/coordinator/coordinator-docker-testnet.config.overrides.toml:/opt/consensys/linea/coordinator/config/coordinator-docker-testnet.config.overrides.toml:ro
      - ../tmp/testnet/:/data/
