version: "3.9"

services:
  sequencer:
    healthcheck:
      test: [ "CMD-SHELL", "sh -c \"[ -f /l2-zkgeth-sequencer/geth/LOCK ]\"" ]
      interval: 1s
      timeout: 1s
      retries: 120
    hostname: sequencer
    container_name: sequencer
    image: consensys/linea-geth:${ZKGETH_TAG:-0588665}
    platform: linux/amd64
    profiles: [ "l2", "l2-bc", "debug" ]
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8550:8550"
      - "30301:30301"
    restart: "no"
    environment:
      DATA_DIR: "/l2-zkgeth-sequencer/"
      BOOTNODE_PORT: '30301'
      NETRESTRICT: "11.11.11.0/24"
      ZKGETH_COUNT_ONLY: "true"
      ZKGETH_DISABLE_TRACES: "true"
      ZKGETH_EMPTY_BLOCK_CREATION: "false"
      ZKGETH_TRACES_LIMITS_FILE: "/config/limits.toml"
      ZKGETH_BLOCK_SIZE_LIMIT: "108592" # 129072(coordinator limit) - 20*1024(safety margin)
      ZKGETH_TRACE_OVERFLOW_NBRETRIES: "10"
      ZKGETH_ADDR_BLACKLIST: "0x0000000000000000000000000000000000000001:0x0000000000000000000000000000000000000002:0x0000000000000000000000000000000000000003:0x0000000000000000000000000000000000000004:0x0000000000000000000000000000000000000005:0x0000000000000000000000000000000000000006:0x0000000000000000000000000000000000000007:0x0000000000000000000000000000000000000008:0x0000000000000000000000000000000000000009"
      MAX_BLOCK_GAS: 10000000  #10M
      MAX_BLOCKDATA_BYTES: 35000 #35 KBytes
      MAX_TXDATA_BYTES: 30000 #30 KBytes
      ETHSTATS_URL: "linea-sequencer:${WS_SECRET:-dummy-secret}@l2-ethstats:3000"
    entrypoint: ""
    command: [ "sh", "/scripts/sequencer.sh", "1337", "/genesis.json", "0x0", "0x1C9C380", "0xF4240", "0x6d976c9b8ceee705d4fe8699b44e5eb58242f484" ]
    volumes:
      - ./geth/scripts:/scripts:ro
      - ./config/linea-local-dev-genesis-PoA.json:/genesis.json:ro
      - ../config/common/traces-limits-v1.toml:/config/limits.toml:ro
      # - ./config/jwt-secret.hex:/jwt-secret.hex:ro
      - ./geth/geth-l2-boot.key:/boot.key:ro
      - ./keystore/L2:/keystore:ro
      - local-dev:/data/
    networks:
      linea:
        ipv4_address: 11.11.11.101

  l2-node:
    environment:
      BOOTNODES: "enode://f94118749beb981da38b82ab6be7b00dc0082783d698080fd0ae45a2c3d42f1ce74cbb153ffcfb1379b64235605bfff43f85b112032ddd9685ad2ab88735e1b1@11.11.11.101:30301"

  traces-node:
    environment:
      BOOTNODES: "enode://f94118749beb981da38b82ab6be7b00dc0082783d698080fd0ae45a2c3d42f1ce74cbb153ffcfb1379b64235605bfff43f85b112032ddd9685ad2ab88735e1b1@11.11.11.101:30301"

  zkbesu-shomei:
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/var/lib/besu/zkbesu-config.toml \
        --genesis-file=/var/lib/besu/genesis.json \
        --min-gas-price=0 \
        --revert-reason-enabled \
        --node-private-key-file=/var/lib/besu/key \
        --plugin-shomei-http-host="11.11.11.114" \
        --plugin-shomei-http-port=8888 \
        --bootnodes=enode://f94118749beb981da38b82ab6be7b00dc0082783d698080fd0ae45a2c3d42f1ce74cbb153ffcfb1379b64235605bfff43f85b112032ddd9685ad2ab88735e1b1@11.11.11.101:30301 \
        --data-path=/traces
