volumes:
  local-dev:
    name: "linea-local-dev"
  logs:
    name: "linea-logs"

networks:
  linea:
    driver: bridge
    ipam:
      config:
        - subnet: 11.11.11.0/24
  l1network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24

# To debug inside the network and volumes
# docker run --rm -it --network=docker_linea -v=linea-local-dev:/data -v=linea-logs:/logs weibeld/ubuntu-networking bash

services:
  l1-el-node:
    extends:
      file: compose-spec-l1-services.yml
      service: l1-el-node

  l1-cl-node:
    extends:
      file: compose-spec-l1-services.yml
      service: l1-cl-node

  l1-node-genesis-generator:
    extends:
      file: compose-spec-l1-services.yml
      service: l1-node-genesis-generator

  sequencer:
    extends:
      file: compose-spec-l2-services.yml
      service: sequencer
    image: consensys/linea-besu-package:${BESU_PACKAGE_TAG:-mainnet-402ebda}
    volumes:
      - ../config/common/traces-limits-besu-v1.toml:/var/lib/besu/traces-limits.toml:ro

  traces-node:
    extends:
      file: compose-spec-l2-services.yml
      service: traces-node

  traces-api:
    extends:
      file: compose-spec-l2-services.yml
      service: traces-api

  prover:
    extends:
      file: compose-spec-l2-services.yml
      service: prover

  coordinator:
    extends:
      file: compose-spec-l2-services.yml
      service: coordinator
    environment:
      config__override__l2-network-gas-pricing__json-rpc-pricing-propagation__disabled: ${DISABLE_JSON_RPC_PRICING_PROPAGATION:-true}
      config__override__type2-state-proof-provider__endpoints: # leave empty to disable
    command: [ 'java', '-Dvertx.configurationFile=/var/lib/coordinator/vertx-options.json', '-Dlog4j2.configurationFile=/var/lib/coordinator/log4j2-dev.xml', '-jar', 'libs/coordinator.jar', '--traces-limits', 'config/traces-limits-v1.toml', '--smart-contract-errors', 'config/smart-contract-errors.toml', '--gas-price-cap-time-of-day-multipliers', 'config/gas-price-cap-time-of-day-multipliers.toml', 'config/coordinator-docker.config.toml', 'config/coordinator-docker-web3signer-override.config.toml' ]
    volumes:
      - ../config/common/traces-limits-v1.toml:/opt/consensys/linea/coordinator/config/traces-limits-v1.toml:ro

  web3signer:
    extends:
      file: compose-spec-l2-services.yml
      service: web3signer

  postgres:
    extends:
      file: compose-spec-l2-services.yml
      service: postgres

  zkbesu-shomei:
    extends:
      file: compose-spec-l2-services.yml
      service: zkbesu-shomei

  shomei:
    extends:
      file: compose-spec-l2-services.yml
      service: shomei
