# data
network="linea-mainnet"
#logging="INFO" log is managed via log4j config file
data-path="/data"

# Sync mode and data layer implementation
sync-mode="SNAP"
data-storage-format="BONSAI"

cache-last-block-headers-preload-enabled=true
cache-last-block-headers=50000

# Min gas price
min-gas-price=1000000

max-peers=50

# Host allow list
host-allowlist=["*"]

# engine
engine-host-allowlist=["*"]
engine-rpc-port=8550
engine-jwt-disabled=false # set to true if want to disable jwt
engine-jwt-secret="/var/lib/besu/jwt"

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ADMIN","DEBUG","NET","ETH","CLIQUE","MINER","WEB3","TRACE"]
rpc-http-cors-origins=["*"]
rpc-http-max-active-connections=20000

# ws
rpc-ws-enabled=true
rpc-ws-api=["ADMIN","DEBUG","NET","ETH","CLIQUE","MINER","WEB3","TRACE"]
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-max-active-connections=200

# graphql
graphql-http-enabled=false

# p2p
p2p-port=30303
fast-sync-min-peers=1
Xdns-enabled=true

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

### Plugin Configuration ###
# Disable external plugins
Xplugins-external-enabled=false
Xeth-capability-max=68
