##
# Time of day multipliers for dynamic gas price cap calculation:
#
# TDM stands for "Time of Day Multiplier" and has a range of values between 0.25 - 1.75.
#
# When we expect the L1 gas price to be low, for example on a Saturday night, the TDM will be at it's highest because
# we want to increase the rate at which we increase the threshold to try and settle within this time window.
# The value will be at it's lowest during peak L1 gas price times, for example, on a Tuesday afternoon, because we
# know it is likely to be expensive during this window.
#
# The values for the TDM based on the 90D of L1 gas price real world data. It is expected that every few months
# we will update this table with the latest data to account for any notable changes in the trends of L1 gas prices.
# It does not account for public holidays yet.
##

[gas-price-cap-time-of-day-multipliers]
SUNDAY_0 = 1.7489178377946066
SUNDAY_1 = 1.7494632175198737
SUNDAY_2 = 1.75
SUNDAY_3 = 1.733166295438555
SUNDAY_4 = 1.6993775444542885
SUNDAY_5 = 1.6350086618091364
SUNDAY_6 = 1.5627740860151331
SUNDAY_7 = 1.4831149222064164
SUNDAY_8 = 1.4101476768256929
SUNDAY_9 = 1.370085278922007
SUNDAY_10 = 1.3516015544068651
SUNDAY_11 = 1.3482404546676368
SUNDAY_12 = 1.3580905751578942
SUNDAY_13 = 1.3775497419563296
SUNDAY_14 = 1.3700255667542938
SUNDAY_15 = 1.2642948506461285
SUNDAY_16 = 1.2794806131912935
SUNDAY_17 = 1.2750892256476676
SUNDAY_18 = 1.2919720208955585
SUNDAY_19 = 1.317984990098603
SUNDAY_20 = 1.4433501639513178
SUNDAY_21 = 1.4705921238901998
SUNDAY_22 = 1.515043370430801
SUNDAY_23 = 1.5556742617266397
MONDAY_0 = 1.5381562278760164
MONDAY_1 = 1.5423761828433993
MONDAY_2 = 1.539015963719092
MONDAY_3 = 1.487676153648977
MONDAY_4 = 1.430973985132037
MONDAY_5 = 1.4656765439056292
MONDAY_6 = 1.4484298622828233
MONDAY_7 = 1.4459076216659752
MONDAY_8 = 1.4899061835032241
MONDAY_9 = 1.5249733712852067
MONDAY_10 = 1.511367489481033
MONDAY_11 = 1.4225695658047797
MONDAY_12 = 1.2887291896624584
MONDAY_13 = 1.1460926897291355
MONDAY_14 = 1.0004897955233254
MONDAY_15 = 0.8694664537368378
MONDAY_16 = 0.8270273375962802
MONDAY_17 = 0.7868289022833883
MONDAY_18 = 0.7780303121746551
MONDAY_19 = 0.7756215256634205
MONDAY_20 = 0.7984895728860915
MONDAY_21 = 0.8918589268832423
MONDAY_22 = 0.9967716668541272
MONDAY_23 = 1.0973334887144106
TUESDAY_0 = 1.2233064209957951
TUESDAY_1 = 1.3238883432855082
TUESDAY_2 = 1.3874518307497257
TUESDAY_3 = 1.463621147171298
TUESDAY_4 = 1.4975989065490154
TUESDAY_5 = 1.481679186141442
TUESDAY_6 = 1.452778387763161
TUESDAY_7 = 1.3414858185569951
TUESDAY_8 = 1.2869454637983988
TUESDAY_9 = 1.249347290389873
TUESDAY_10 = 1.196488297386161
TUESDAY_11 = 1.1136140507034202
TUESDAY_12 = 0.9867528660797885
TUESDAY_13 = 0.8018989158195754
TUESDAY_14 = 0.6173048748109258
TUESDAY_15 = 0.46718586671750373
TUESDAY_16 = 0.4103633833041902
TUESDAY_17 = 0.4871260756989506
TUESDAY_18 = 0.5667378483016126
TUESDAY_19 = 0.6464203510900723
TUESDAY_20 = 0.7780268325299871
TUESDAY_21 = 0.8995921101255763
TUESDAY_22 = 1.0077600114996088
TUESDAY_23 = 1.1109769960680498
WEDNESDAY_0 = 1.2097668746150059
WEDNESDAY_1 = 1.2631002319009361
WEDNESDAY_2 = 1.2912775191940549
WEDNESDAY_3 = 1.3229785939630059
WEDNESDAY_4 = 1.3428607301494424
WEDNESDAY_5 = 1.3750788517823973
WEDNESDAY_6 = 1.3752344527256497
WEDNESDAY_7 = 1.3505490078766218
WEDNESDAY_8 = 1.2598503219367945
WEDNESDAY_9 = 1.2051668977452374
WEDNESDAY_10 = 1.0320896222195326
WEDNESDAY_11 = 0.8900138031631949
WEDNESDAY_12 = 0.6341155208698448
WEDNESDAY_13 = 0.48337590254714624
WEDNESDAY_14 = 0.2903189399226416
WEDNESDAY_15 = 0.25
WEDNESDAY_16 = 0.25711039485046006
WEDNESDAY_17 = 0.37307641907591793
WEDNESDAY_18 = 0.45280799454961196
WEDNESDAY_19 = 0.5631397823847637
WEDNESDAY_20 = 0.6285005244224133
WEDNESDAY_21 = 0.6671897537279405
WEDNESDAY_22 = 0.7268406397452634
WEDNESDAY_23 = 0.8068904097486369
THURSDAY_0 = 0.9021601102971811
THURSDAY_1 = 1.023741688964238
THURSDAY_2 = 1.1340689935096755
THURSDAY_3 = 1.2530130345819006
THURSDAY_4 = 1.3163421664973542
THURSDAY_5 = 1.3536343767230727
THURSDAY_6 = 1.3432290485306728
THURSDAY_7 = 1.2864983218982178
THURSDAY_8 = 1.2320488534113174
THURSDAY_9 = 1.1984530721079034
THURSDAY_10 = 1.0877338251341975
THURSDAY_11 = 0.9999324929016475
THURSDAY_12 = 0.87536726762619
THURSDAY_13 = 0.6560822412167919
THURSDAY_14 = 0.44836474861432074
THURSDAY_15 = 0.36145134935025247
THURSDAY_16 = 0.2695997829759713
THURSDAY_17 = 0.2898426312618241
THURSDAY_18 = 0.3970093434340387
THURSDAY_19 = 0.5193273246848977
THURSDAY_20 = 0.6426415257034419
THURSDAY_21 = 0.800685718218497
THURSDAY_22 = 0.9215516833839711
THURSDAY_23 = 1.053701659160912
FRIDAY_0 = 1.149649788723893
FRIDAY_1 = 1.2046315447861193
FRIDAY_2 = 1.2724031281576726
FRIDAY_3 = 1.3525693456352732
FRIDAY_4 = 1.3746126314960814
FRIDAY_5 = 1.3744591862592468
FRIDAY_6 = 1.3297812543035683
FRIDAY_7 = 1.2762064429631657
FRIDAY_8 = 1.235662409263294
FRIDAY_9 = 1.2171558028785991
FRIDAY_10 = 1.182722399785398
FRIDAY_11 = 1.137345538963285
FRIDAY_12 = 0.9999308422620752
FRIDAY_13 = 0.8055000309055653
FRIDAY_14 = 0.5667135273493851
FRIDAY_15 = 0.4081529603000651
FRIDAY_16 = 0.3987031354907009
FRIDAY_17 = 0.5030075499003412
FRIDAY_18 = 0.6518159532641841
FRIDAY_19 = 0.8733483414970974
FRIDAY_20 = 1.0496224913080463
FRIDAY_21 = 1.1820684558591705
FRIDAY_22 = 1.2561688567574458
FRIDAY_23 = 1.3204704912328773
SATURDAY_0 = 1.3832230236620218
SATURDAY_1 = 1.4632908341022142
SATURDAY_2 = 1.5019230781315296
SATURDAY_3 = 1.5437332506007084
SATURDAY_4 = 1.5934153179751855
SATURDAY_5 = 1.6245578072557723
SATURDAY_6 = 1.6294919789890665
SATURDAY_7 = 1.6027665451672717
SATURDAY_8 = 1.6068061069158674
SATURDAY_9 = 1.624257927970777
SATURDAY_10 = 1.5996112411089
SATURDAY_11 = 1.5659672993092648
SATURDAY_12 = 1.5333537902522736
SATURDAY_13 = 1.445292929996356
SATURDAY_14 = 1.2966021477035259
SATURDAY_15 = 1.250999408961155
SATURDAY_16 = 1.2535364828163025
SATURDAY_17 = 1.2736456128871074
SATURDAY_18 = 1.3348268054897328
SATURDAY_19 = 1.4571388900094875
SATURDAY_20 = 1.5073787902995706
SATURDAY_21 = 1.5605139580010123
SATURDAY_22 = 1.5885303316932382
SATURDAY_23 = 1.6169891066719597
