[traces-limits]
#
# Arithmetization module limits
#
ADD                 = 262144
BIN                 = 262144
BLAKE_MODEXP_DATA   = 16384
BLOCK_DATA          = 4096
BLOCK_HASH          = 2048
EC_DATA             = 65536
EUC                 = 65536
EXP                 = 65536
EXT                 = 524288
GAS                 = 65536
HUB                 = 2097152
LOG_DATA            = 65536
LOG_INFO            = 4096
MMIO                = 2097152
MMU                 = 1048576
MOD                 = 131072
MUL                 = 65536
MXP                 = 524288
OOB                 = 262144
RLP_ADDR            = 4096
RLP_TXN             = 131072
RLP_TXN_RCPT        = 65536
ROM                 = 8388608 # Note: set as 6291456 in production as workaround
ROM_LEX             = 1024
SHAKIRA_DATA        = 65536
SHF                 = 262144
STP                 = 16384
TRM                 = 32768
TXN_DATA            = 8192
WCP                 = 262144
#
# Reference table limits, set to Integer.MAX_VALUE
#
BIN_REFERENCE_TABLE = 2147483647
SHF_REFERENCE_TABLE = 2147483647
INSTRUCTION_DECODER = 2147483647
#
# Precompiles limits
#
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS        = 128
PRECOMPILE_SHA2_BLOCKS                      = 200
PRECOMPILE_RIPEMD_BLOCKS                    = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALLS           = 32
PRECOMPILE_ECADD_EFFECTIVE_CALLS            = 1024
PRECOMPILE_ECMUL_EFFECTIVE_CALLS            = 40
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS  = 16
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS    = 64
PRECOMPILE_ECPAIRING_MILLER_LOOPS           = 64
PRECOMPILE_BLAKE_EFFECTIVE_CALLS            = 0
PRECOMPILE_BLAKE_ROUNDS                     = 0
#
# Block-specific limits
#
BLOCK_KECCAK        = 8192
BLOCK_L1_SIZE       = 1000000
BLOCK_L2_L1_LOGS    = 16
BLOCK_TRANSACTIONS  = 300
