[traces-limits]
# Module limits of the beta-v4.4 release (Osaka)
#
# Arithmetization module limits
#
ADD                 = 262144
BLAKE_MODEXP_DATA   = 16384
BLOCK_DATA          = 4096
BLOCK_HASH          = 2560
BLS_DATA            = 65536
EC_DATA             = 65536
EUC                 = 65536
EXP                 = 65536
EXT                 = 524288
GAS                 = 65536
HUB                 = 2097152
LOG_DATA            = 65536
LOG_INFO            = 4096
MMIO                = 2097152
MMU                 = 1048576
MOD                 = 131072
MUL                 = 65536
MXP                 = 524288
OOB                 = 262144
RLP_ADDR            = 4096
RLP_AUTH            = 16384
RLP_TXN             = 131072
RLP_TXN_RCPT        = 65536
RLP_UTILS           = 131072
ROM                 = 8388608
ROM_LEX             = 1024
SHAKIRA_DATA        = 65536
SHF                 = 262144
STP                 = 16384
TRM                 = 32768
TXN_DATA            = 8192
WCP                 = 262144
#
# Precompiles limits
#
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS        = 128
PRECOMPILE_SHA2_BLOCKS                      = 200
PRECOMPILE_RIPEMD_BLOCKS                    = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALLS           = 32
PRECOMPILE_LARGE_MODEXP_EFFECTIVE_CALLS     = 1
PRECOMPILE_ECADD_EFFECTIVE_CALLS            = 256
PRECOMPILE_ECMUL_EFFECTIVE_CALLS            = 40
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS  = 16
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS    = 64
PRECOMPILE_ECPAIRING_MILLER_LOOPS           = 64
PRECOMPILE_BLAKE_EFFECTIVE_CALLS            = 0
PRECOMPILE_BLAKE_ROUNDS                     = 0
# Precompiles introduced from beta-v4.0-rc6-CANCUN
PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS     = 1
PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS = 2
PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS               = 4
PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS               = 4
PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS           = 8
PRECOMPILE_BLS_FINAL_EXPONENTIATIONS                = 2
PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS         = 4
PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS        = 4
PRECOMPILE_BLS_C1_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS                  = 8
PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS                  = 8
# Precompiles introduced from beta-v4.4
PRECOMPILE_P256_VERIFY_EFFECTIVE_CALLS              = 128
#
# Block-specific limits
#
BLOCK_KECCAK        = 8192
BLOCK_L1_SIZE       = 1000000
BLOCK_L2_L1_LOGS    = 16
BLOCK_TRANSACTIONS  = 300

