[traces-limits]
# Module limits of the beta-v4.4 release (Osaka)
#
# Arithmetization module limits
#
ADD                 = 524288
BIN                 = 524288
BLAKE_MODEXP_DATA   = 32768
BLOCK_DATA          = 8192
BLOCK_HASH          = 8192
BLS_DATA            = 131072
EC_DATA             = 131072
EUC                 = 131072
EXP                 = 131072
EXT                 = 1048576
GAS                 = 131072
HUB                 = 4194304
LOG_DATA            = 131072
LOG_INFO            = 8192
MMIO                = 4194304
MMU                 = 2097152
MOD                 = 262144
MUL                 = 131072
MXP                 = 1048576
OOB                 = 524288
RLP_ADDR            = 8192
RLP_TXN             = 262144
RLP_TXN_RCPT        = 131072
RLP_UTILS           = 262144
ROM                 = 16777216
ROM_LEX             = 2048
SHAKIRA_DATA        = 131072
SHF                 = 524288
STP                 = 32768
TRM                 = 65536
TXN_DATA            = 16384
WCP                 = 524288
#
# Precompiles limits
#
PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS        = 256
PRECOMPILE_SHA2_BLOCKS                      = 400
PRECOMPILE_RIPEMD_BLOCKS                    = 0
PRECOMPILE_MODEXP_EFFECTIVE_CALLS           = 64
PRECOMPILE_LARGE_MODEXP_EFFECTIVE_CALLS     = 2
PRECOMPILE_ECADD_EFFECTIVE_CALLS            = 512
PRECOMPILE_ECMUL_EFFECTIVE_CALLS            = 80
PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS  = 32
PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS    = 128
PRECOMPILE_ECPAIRING_MILLER_LOOPS           = 128
PRECOMPILE_BLAKE_EFFECTIVE_CALLS            = 0
PRECOMPILE_BLAKE_ROUNDS                     = 0
# Precompiles introduced from beta-v4.0-rc6-CANCUN
PRECOMPILE_BLS_POINT_EVALUATION_EFFECTIVE_CALLS     = 2
PRECOMPILE_POINT_EVALUATION_FAILURE_EFFECTIVE_CALLS = 4
PRECOMPILE_BLS_G1_ADD_EFFECTIVE_CALLS               = 16
PRECOMPILE_BLS_G1_MSM_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_G2_ADD_EFFECTIVE_CALLS               = 16
PRECOMPILE_BLS_G2_MSM_EFFECTIVE_CALLS               = 8
PRECOMPILE_BLS_PAIRING_CHECK_MILLER_LOOPS           = 16
PRECOMPILE_BLS_FINAL_EXPONENTIATIONS                = 4
PRECOMPILE_BLS_MAP_FP_TO_G1_EFFECTIVE_CALLS         = 8
PRECOMPILE_BLS_MAP_FP2_TO_G2_EFFECTIVE_CALLS        = 8
PRECOMPILE_BLS_C1_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_C2_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_G1_MEMBERSHIP_CALLS                  = 16
PRECOMPILE_BLS_G2_MEMBERSHIP_CALLS                  = 16
# Precompiles introduced from beta-v4.4
PRECOMPILE_P256_VERIFY_EFFECTIVE_CALLS              = 256
#
# Block-specific limits
#
BLOCK_KECCAK        = 8192
BLOCK_L1_SIZE       = 120000
BLOCK_L2_L1_LOGS    = 16
BLOCK_TRANSACTIONS  = 1000