permissions: read-all
name: Weekly Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly-unit-tests-prague:
    uses: ./.github/workflows/reusable-weekly-tests.yml
    secrets: inherit
    with:
      zkevm_fork: PRAGUE

  weekly-prc-call-tests-prague:
    uses: ./.github/workflows/reusable-weekly-prc-tests.yml
    secrets: inherit
    with:
      zkevm_fork: PRAGUE
