permissions: read-all
name: Weekly Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly-unit-tests-prague:
    uses: ./.github/workflows/reusable-weekly-tests.yml
    secrets: inherit
    with:
      zkevm_fork: PRAGUE

  weekly-unit-tests-osaka:
    uses: ./.github/workflows/reusable-weekly-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA

  weekly-prc-call-tests-prague:
    uses: ./.github/workflows/reusable-weekly-prc-tests.yml
    secrets: inherit
    with:
      zkevm_fork: PRAGUE

  weekly-prc-call-tests-osaka:
    uses: ./.github/workflows/reusable-weekly-prc-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA

  weekly-replay-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment

      - name: Run Weekly Replay tests
        run: GOMAXPROCS=10 GOMEMLIMIT=20GiB ./gradlew weeklyReplayTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          GOCORSET_FLAGS: -v --ansi-escapes=false --report --air
          JUNIT_TESTS_PARALLELISM: 2

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: weekly-replay-tests-report
          path: arithmetization/build/reports/tests/**/*

      - name: Failure Notification
        if: github.ref == 'refs/heads/arith-dev' && (failure() || cancelled())
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            name: "WeeklyReplay"
            status: "${{ job.status }}"
