name: Nightly Tests

on:
  schedule:
    - cron: "0 22 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          go-corset: true

      - name: Run Nightly tests
        run: GOMEMLIMIT=32GiB ./gradlew nightlyTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -vw --ansi-escapes=false --report --mir
          ZKEVM_BIN: "zkevm.bin"
          NIGHTLY_TESTS_PARALLELISM: 2

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: nightly-tests-report
          path: build/reports/tests/**/*

      - name: Upload jacoco nightly tests coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-nightly-tests-coverage-report
          path: arithmetization/build/reports/jacoco/jacocoNightlyTestsReport/**/*

      - name: Upload jacoco nightly tests exec file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-nightly-tests-exec-file
          path: arithmetization/build/jacoco/nightlyTests.exec

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Nightly"
             status: "${{ job.status }}"
