name: Daily State Tests

on:
  schedule:
    - cron: "0 23 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ethereum-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          go-corset: true

      - name: Generate General State Reference Tests
        run: ./gradlew generateGeneralStateReferenceTests -Dorg.gradle.caching=true
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false

      - name: Run General State Reference Tests
        run: GOMEMLIMIT=20GiB ./gradlew referenceGeneralStateTests
        env:
          REFERENCE_TESTS_PARALLELISM: 4
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -vw -b1024 --ansi-escapes=false --report --air

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ethereum-tests-report
          path: |
            reference-tests/build/reports/tests/**/*
            tmp/local/*

      - name: Upload jacoco state tests coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-state-tests-coverage-report
          path: reference-tests/build/reports/jacoco/jacocoReferenceGeneralStateTestsReport/**/*

      - name: Upload jacoco state tests exec file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-state-tests-exec-file
          path: reference-tests/build/jacoco/referenceGeneralStateTests.exec

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Daily State (Go Corset)"
             status: "${{ job.status }}"
