name: reference tests

on:
  schedule:
    - cron: "0 23 * * 1-5"
  workflow_dispatch:

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  ethereum-tests:
    runs-on: [self-hosted, Linux, X64, xxlarge]
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CONSTRAINTS_SSH_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Corset
        run: RUSTFLAGS=-Awarnings cargo install --git ssh://git@github.com/ConsenSys/corset --tag v9.7.14 --locked --force

      - name: Generate zkevm_for_reference_tests.bin
        run: cd ./linea-constraints; make zkevm_for_reference_tests.bin -B; cd ..

      - name: Generate General State Reference Tests
        run:  ./gradlew generateGeneralStateReferenceTests -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Run General State Reference Tests
        run: ./gradlew referenceGeneralStateTests
        env:
          REFERENCE_TESTS_PARALLELISM: 10
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ethereum-tests-report
          path: reference-tests/build/reports/tests/**/*


  ethereum-tests-go-corset:
    runs-on: [self-hosted, Linux, X64, xxlarge]
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.CONSTRAINTS_SSH_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Corset
        run: RUSTFLAGS=-Awarnings cargo install --git ssh://git@github.com/ConsenSys/corset --tag v9.7.14 --locked --force

      - name: Generate zkevm_for_reference_tests.bin
        run: cd ./linea-constraints; make zkevm_for_reference_tests.bin -B; cd ..

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      - name: Install Go Corset
        run: go install github.com/consensys/go-corset/cmd/go-corset@latest

      - name: Generate General State Reference Tests
        run: ./gradlew generateGeneralStateReferenceTests -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand

      - name: Run General State Reference Tests
        run: GOMEMLIMIT=196GiB ./gradlew referenceGeneralStateTests
        env:
          REFERENCE_TESTS_PARALLELISM: 10
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -wd --ansi-escapes=false --report --air

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ethereum-tests-go-corset-report
          path: reference-tests/build/reports/tests/**/*
