name: Weekly Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          rust-corset: true

      - name: Run Weekly tests
        run: ./gradlew weeklyTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: fields,expand,expand,expand
          WEEKLY_TESTS_PARALLELISM: 4

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-tests-report
          path: build/reports/tests/**/*

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Weekly (Go-Corset)"
             status: "${{ job.status }}"

  weekly-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          go-corset: true

      - name: Run Weekly tests
        run: GOMEMLIMIT=96GiB ./gradlew weeklyTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -vw -b1024 --ansi-escapes=false --report --air

      - name: Failure Notification
        if: ${{ failure() || cancelled() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
             name: "Weekly (Go-Corset)"
             status: "${{ job.status }}"
