name: Weekly Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly-unit-tests-london:
    uses: ./.github/workflows/reusable-weekly-tests.yml
    secrets: inherit
    with:
      zkevm_fork: LONDON

  weekly-unit-tests-shanghai:
    uses: ./.github/workflows/reusable-weekly-tests.yml
    secrets: inherit    
    with:
      zkevm_fork: SHANGHAI

  weekly-prc-call-tests-london:
    uses: ./.github/workflows/reusable-weekly-prc-tests.yml
    secrets: inherit    
    with:
      zkevm_fork: LONDON

  weekly-prc-call-tests-shanghai:
    uses: ./.github/workflows/reusable-weekly-prc-tests.yml
    secrets: inherit    
    with:
      zkevm_fork: SHANGHAI
