name: "Unit & Fast Replay Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      tests-with-ssh:
        description: Run tests with ability to ssh into environment
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ==================================================================
  # Build
  # ==================================================================
  build:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Build without tests
        run: ./gradlew build -x test -x spotlessCheck
        env:
          JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: arithmetization/build/libs

      - name: Run spotless
        run: ./gradlew --no-daemon --parallel clean spotlessCheck

  # ==================================================================
  # Unit Tests
  # ==================================================================
  unit-tests-london:
    needs: [ build ]
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      zkevm_fork: LONDON
      tests-with-ssh: ${{ inputs.tests-with-ssh || false }}

  unit-tests-shanghai:
    needs: [ build ]
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      zkevm_fork: SHANGHAI
      tests-with-ssh: ${{ inputs.tests-with-ssh || false}}

  unit-tests-cancun:
    needs: [ build ]
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      zkevm_fork: CANCUN
      tests-with-ssh: ${{ inputs.tests-with-ssh || false}}

  # ==================================================================
  # Fast Replay Tests
  # ==================================================================
  replay-tests:
    needs: [ build ]
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          enable-ssh: ${{ inputs.tests-with-ssh }}

      - name: Run replay tests
        run: GOMEMLIMIT=26GiB ./gradlew :arithmetization:fastReplayTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          REPLAY_TESTS_PARALLELISM: 4
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -b1024 -v --ansi-escapes=false --report --air
          ZKEVM_FORK: LONDON

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: replay-tests-report
          path: arithmetization/build/reports/tests/**/*

      - name: Upload jacoco fast replay tests coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-fast-replay-tests-coverage-report
          path: arithmetization/build/reports/jacoco/jacocoFastReplayTestsReport/**/*

      - name: Upload jacoco fast replay tests exec file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-fast-replay-tests-exec-file
          path: arithmetization/build/jacoco/fastReplayTests.exec
