name: Hub-Shomei-Besu-Integration

on:
  workflow_dispatch:
    inputs:
      tests-with-ssh:
        description: Run tests with ability to ssh into environment
        required: false
        type: boolean
        default: false


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests-with-besu-node:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          enable-ssh: ${{ inputs.tests-with-ssh }}

      - name: Run unit tests
        run: GOMEMLIMIT=26GiB ./gradlew :arithmetization:besuNodeTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -b1024 -v --ansi-escapes=false --report --air


      - name: Upload proof request and conflation files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces-proof-requests
          path: arithmetization/build/besu/traces/**/*
          compression-level: 9
          if-no-files-found: 'error'