name: "Reusable weekly prc call tests workflow"

on:
  workflow_call:
    inputs:
      zkevm_fork:
        required: true
        type: string

jobs:
  # ==================================================================
  # Weekly PRC Call Tests
  # ==================================================================
  weekly-prc-calltests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment

      - name: Run Precompile Call tests
        run: GOMAXPROCS=1 GOMEMLIMIT=10GiB ./gradlew prcCallTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          JUNIT_TESTS_PARALLELISM: 24
          GOCORSET_FLAGS: -v -b1024 --ansi-escapes=false --report --mir
          ZKEVM_FORK: ${{ inputs.zkevm_fork }}

      - name: Upload prc calls test report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: prc-call-tests-report-${{ inputs.zkevm_fork }}
          path: arithmetization/build/reports/tests/**/*

      - name: Upload jacoco weekly prc-call tests coverage report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: jacoco-prc-call-tests-coverage-report-${{ inputs.zkevm_fork }}
          path: arithmetization/build/reports/jacoco/jacocoPrcCallTestsReport/**/*

      - name: Upload jacoco weekly prc-call tests exec file
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: jacoco-prc-call-tests-exec-file-${{ inputs.zkevm_fork }}
          path: arithmetization/build/jacoco/prcCallTests.exec

      - name: Failure Notification
        if: github.ref == 'refs/heads/arith-dev' && (failure() || cancelled())
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            name: "Weekly Precompile call"
            status: "${{ job.status }}"
