name: "Reusable unit tests workflow"

on:
  workflow_call:
    inputs:
      zkevm_fork:
        required: true
        type: string
      tests-with-ssh:
        required: true
        type: boolean

jobs:
  # ==================================================================
  # Unit Tests
  # ==================================================================
  unit-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Test Environment
        uses: ./.github/actions/setup-environment
        with:
          enable-ssh: ${{ inputs.tests-with-ssh }}

      - name: Run unit tests
        run: GOMEMLIMIT=26GiB ./gradlew :arithmetization:test
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          CORSET_FLAGS: disable
          GOCORSET_FLAGS: -b1024 -v --ansi-escapes=false --report --air
          UNIT_TESTS_PARALLELISM: 4
          ZKEVM_FORK: ${{ inputs.zkevm_fork }}

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report-${{ inputs.zkevm_fork }}
          path: arithmetization/build/reports/tests/**/*

      - name: Upload jacoco unit tests coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-unit-tests-coverage-report-${{ inputs.zkevm_fork }}
          path: arithmetization/build/reports/jacoco/test/**/*

      - name: Upload jacoco unit tests exec file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-unit-tests-exec-file-${{ inputs.zkevm_fork }}
          path: arithmetization/build/jacoco/test.exec
