name: "Validate One Blockchain Test"
permissions:
  contents: read
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # run only one specific blockchain reference test for validation
  validation-reference-test-flow:
    uses: ./.github/workflows/reusable-blockchain-tests.yml
    secrets: inherit
    with:
      zkevm_fork: PRAGUE
      test_filter: ${{ 'BlockchainReferenceTest_10' }}
      failed_module: ${{ inputs.failed_module || '' }}
      failed_constraint: ${{ inputs.failed_constraint || '' }}
      commit: ${{ inputs.commit || '' }}
