name: native-yield-automation-service-testing

permissions:
  contents: read
  actions: read

on:
  workflow_call:

concurrency:
  group: native-yield-automation-service-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-med
    name: native-yield-automation-service-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs environment
        uses: ./.github/actions/setup-nodejs

      - name: Build
        run: |
          pnpm --filter @consensys/linea-shared-utils build
          pnpm --filter @consensys/linea-native-yield-automation-service build

      - name: Run tests and generate coverage report
        run: |
          pnpm --filter @consensys/linea-shared-utils test
          pnpm --filter @consensys/linea-native-yield-automation-service test
