name: postman-and-SDK-testing

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

concurrency:
  group: postman-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  run-tests:
    runs-on: [self-hosted, ubuntu-22.04, X64, small]
    name: Postman & SDK tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup nodejs environment
        uses: ./.github/actions/setup-nodejs

      - name: Run tests and generate coverage report
        env:
          NATIVE_LIBS_RELEASE_TAG: blob-libs-v1.0.1
        run: |
          pnpm run -F ./ts-libs/linea-native-libs build;
          pnpm run -F ./sdk build;
          pnpm run -F ./sdk test;
