name: "Reusable tracer weekly prc call tests workflow"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      zkevm_fork:
        required: true
        type: string

jobs:
  # ==================================================================
  # Weekly PRC Call Tests
  # ==================================================================
  weekly-prc-calltests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Setup Tracer Test Environment
        uses: ./.github/actions/setup-tracer-environment

      - name: Run Precompile Call tests
        run: GOMAXPROCS=1 GOMEMLIMIT=10GiB ./gradlew :tracer:arithmetization:prcCallTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          JUNIT_TESTS_PARALLELISM: 24
          GOCORSET_FLAGS: -v -b1024 --ansi-escapes=false --report --mir
          ZKEVM_FORK: ${{ inputs.zkevm_fork }}

      - name: Upload prc calls test report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: prc-call-tests-report-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/reports/tests/**/*

      - name: Upload jacoco weekly prc-call tests coverage report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jacoco-prc-call-tests-coverage-report-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/reports/jacoco/jacocoPrcCallTestsReport/**/*

      - name: Upload jacoco weekly prc-call tests exec file
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jacoco-prc-call-tests-exec-file-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/jacoco/prcCallTests.exec
