name: "Reusable tracer weekly tests workflow"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      zkevm_fork:
        required: true
        type: string

jobs:
  # ==================================================================
  # Weekly Tests
  # ==================================================================
  weekly-unit-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive

      - name: Setup Tracer Test Environment
        uses: ./.github/actions/setup-tracer-environment

      - name: Run Weekly tests
        run: GOMAXPROCS=10 GOMEMLIMIT=20GiB ./gradlew :tracer:arithmetization:weeklyTest
        env:
          JUNIT_TESTS_PARALLELISM: 2
          GOCORSET_FLAGS: -v -b1024 --ansi-escapes=false --report --mir
          ZKEVM_FORK: ${{ inputs.zkevm_fork }}

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: weekly-tests-report-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/reports/tests/**/*

      - name: Upload jacoco weekly tests coverage report
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jacoco-weekly-tests-coverage-report-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/reports/jacoco/jacocoWeeklyTestsReport/**/*

      - name: Upload jacoco weekly tests exec file
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jacoco-weekly-tests-exec-file-${{ inputs.zkevm_fork }}
          path: tracer/arithmetization/build/jacoco/weeklyTests.exec

      - name: Failure Notification
        if: github.ref == 'refs/heads/main' && (failure() || cancelled())
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            name: "Weekly Unit"
            status: "${{ job.status }}"
