name: Reusable linea-besu-package build, test, and push

permissions:
  contents: write
  actions: read
  packages: write

on:
  workflow_call:
    inputs:
      release_tag_prefix:
        required: true
        type: string
      run_test:
        required: true
        type: boolean
      run_e2e_test:
        required: true
        type: boolean
      push_image:
        required: true
        type: boolean
      skip_e2e_test:
        required: true
        type: boolean
      expected_traces_api_ver:
        required: true
        type: string
      with_besu_fleet_plugin:
        required: true
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
      FLEET_GITHUB_APP_ID:
        required: false
      FLEET_GITHUB_APP_PRIVATE_KEY:
        required: false

jobs:
  build-and-upload-artifact:
    uses: ./.github/workflows/linea-besu-package-build-and-upload.yml
    if: ${{ inputs.run_test || inputs.run_e2e_test }}
    with:
      release_tag_prefix: ${{ inputs.release_tag_prefix }}
      with_besu_fleet_plugin: ${{ inputs.with_besu_fleet_plugin }}
    secrets: inherit

  run-test:
    needs: [ build-and-upload-artifact ]
    if: ${{ inputs.run_test }}
    concurrency:
      group: run-test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/reuse-linea-besu-package-run-test.yml
    with:
      dockerimage: ${{ needs.build-and-upload-artifact.outputs.dockerimage }}

  run-e2e-tests:
    needs: [ build-and-upload-artifact ]
    if: ${{ inputs.run_e2e_test && !inputs.skip_e2e_test }}
    concurrency:
      group: run-e2e-tests-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/reuse-linea-besu-package-run-e2e-tests.yml
    with:
      linea_besu_package_tag: ${{ needs.build-and-upload-artifact.outputs.linea_besu_package_tag }}
      expected_traces_api_version: ${{ inputs.expected_traces_api_ver || needs.build-and-upload-artifact.outputs.expected_traces_api_version }}
      e2e-tests-logs-dump: true
      e2e-tests-with-besu-fleet: ${{ inputs.with_besu_fleet_plugin }}
    secrets: inherit

  build-and-push-dockerhub:
    needs: [ run-test, run-e2e-tests ]
    if: ${{ always() && !cancelled() && inputs.push_image && (inputs.skip_e2e_test || needs.run-e2e-test.result == 'skipped' || needs.run-e2e-tests.outputs.tests_outcome == 'success') && (needs.run-test.result == 'skipped' || needs.run-test.result == 'success') }}
    runs-on: gha-runner-scale-set-ubuntu-24-amd64-med
    environment: dockerhub
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build the linea artifacts
        id: assemble
        uses: ./.github/actions/linea-besu-package/assemble
        with:
          release_tag_prefix: ${{ inputs.release_tag_prefix }}
          fetch_besu_fleet_plugin: ${{ inputs.with_besu_fleet_plugin }}
          fleet_github_app_id: ${{ secrets.FLEET_GITHUB_APP_ID }}
          fleet_github_app_private_key: ${{ secrets.FLEET_GITHUB_APP_PRIVATE_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #v3.6.0

      - name: set up docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

      - name: Login to Docker Hub
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set docker build args
        run: |
          echo "Building docker image (without fleet): consensys/linea-besu-package:${{ steps.assemble.outputs.dockertag }}"
          if [[ "${{ inputs.with_besu_fleet_plugin }}" == "true" ]]; then
            echo "Building docker image (with fleet): consensys/linea-besu-package-with-fleet:${{ steps.assemble.outputs.dockertag }}"
          fi

      - name: build and push the combined manifest (if Besu fleet plugin is included)
        if: ${{ inputs.with_besu_fleet_plugin }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: linea-besu-package/linea-besu/.
          platforms: linux/arm64,linux/amd64
          provenance: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ steps.assemble.outputs.dockertag }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.assemble.outputs.build_date }}
          push: true
          tags: |
            consensys/linea-besu-package-with-fleet:${{ steps.assemble.outputs.dockertag }}

      - name: get versions via dotenv
        id: dotenv
        uses: falti/dotenv-action@a33be0b8cf6a6e6f1b82cc9f3782061ab1022be5 #v1.1.4
        with:
          path: linea-besu-package/versions.env
          mode: development
          keys-case: lower
          log-variables: true
          load-mode: strict

      - name: Calculate the checksum of Besu fleet plugin
        id: besu-fleet-plugin-checksum
        if: ${{ inputs.with_besu_fleet_plugin }}
        shell: bash
        run: |
          echo "sha256sum=$(sha256sum linea-besu-package/linea-besu/besu/plugins/besu-fleet-plugin-${{ steps.dotenv.outputs.BESU_FLEET_PLUGIN_VERSION }}.jar | awk '{ print $1 }' )" >> $GITHUB_OUTPUT

      - name: Remove the Besu fleet plugin after image build (if existed)
        shell: bash
        run: |
          rm -fr linea-besu-package/linea-besu/besu/plugins/besu-fleet-plugin* || true

      - name: build and push the combined manifest (without Besu fleet plugin)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: linea-besu-package/linea-besu/.
          platforms: linux/arm64,linux/amd64
          provenance: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            VERSION=${{ steps.assemble.outputs.dockertag }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.assemble.outputs.build_date }}
          push: true
          tags: |
            consensys/linea-besu-package:${{ steps.assemble.outputs.dockertag }}
            ${{ github.ref == 'refs/heads/main' && 'consensys/linea-besu-package:develop' || '' }}
            ${{ github.event_name == 'workflow_dispatch' && 'consensys/linea-besu-package:latest' || '' }}

      ### update the release notes with docker hashes
      - name: create the release notes and then the release
        id: release_create_artifacts
        run: |
          mkdir release && cd release
          tar -czvf linea-besu-package-${{ steps.assemble.outputs.dockertag }}.tar.gz ../linea-besu-package/linea-besu/
          echo "# Release Artifact: Linea Besu Package" > output.md
          echo "**Name:** linea-besu-package-${{ steps.assemble.outputs.dockertag }}.tar.gz" >> output.md
          echo "**SHA256:** $(sha256sum linea-besu-package-${{ steps.assemble.outputs.dockertag }}.tar.gz | awk '{ print $1 }' )" >> output.md
          echo "**From:** [${{ github.ref_name }} (${{ github.event_name }})](https://github.com/Consensys/linea-monorepo/actions/runs/${{ github.run_id }})" >> output.md
          echo "" >> output.md

          echo "### Besu and Plugin Details" >> output.md
          echo "| Module | Version | SHA-256 |" >> output.md
          echo "|--------|---------|--------------|" >> output.md
          echo "| linea-besu | ${{ steps.dotenv.outputs.LINEA_BESU_TAR_GZ }} | $(sha256sum ../linea-besu-package/tmp/${{ steps.dotenv.outputs.LINEA_BESU_FILENAME_PREFIX }}-${{ steps.dotenv.outputs.LINEA_BESU_TAR_GZ }}.tar.gz | awk '{ print $1 }' ) |" >> output.md
          echo "| linea-sequencer-plugin | ${{ steps.dotenv.outputs.LINEA_SEQUENCER_PLUGIN_VERSION }} | $(sha256sum ../linea-besu-package/linea-besu/besu/plugins/linea-sequencer-v${{ steps.dotenv.outputs.LINEA_SEQUENCER_PLUGIN_VERSION }}.jar | awk '{ print $1 }' ) |" >> output.md
          echo "| linea-tracer-plugin | ${{ steps.dotenv.outputs.LINEA_TRACER_PLUGIN_VERSION }} | $(sha256sum ../linea-besu-package/linea-besu/besu/plugins/linea-tracer-${{ steps.dotenv.outputs.LINEA_TRACER_PLUGIN_VERSION }}.jar | awk '{ print $1 }' ) |" >> output.md
          echo "| linea-staterecovery-plugin | ${{ steps.dotenv.outputs.LINEA_STATERECOVERY_PLUGIN_VERSION }} | $(sha256sum ../linea-besu-package/linea-besu/besu/plugins/linea-staterecovery-besu-plugin-v${{ steps.dotenv.outputs.LINEA_STATERECOVERY_PLUGIN_VERSION }}.jar | awk '{ print $1 }' ) |" >> output.md
          echo "| shomei-plugin | ${{ steps.dotenv.outputs.SHOMEI_PLUGIN_VERSION }} | $(sha256sum ../linea-besu-package/linea-besu/besu/plugins/besu-shomei-plugin-v${{ steps.dotenv.outputs.SHOMEI_PLUGIN_VERSION }}.jar | awk '{ print $1 }' ) |" >> output.md
          if [[ "${{ inputs.with_besu_fleet_plugin }}" == "true" ]]; then
            echo "| besu-fleet-plugin | ${{ steps.dotenv.outputs.BESU_FLEET_PLUGIN_VERSION }} | ${{ steps.besu-fleet-plugin-checksum.outputs.sha256sum }} |" >> output.md
          fi
          echo "" >> output.md

          MANIFEST=$(docker manifest inspect consensys/linea-besu-package:${{ steps.assemble.outputs.dockertag }})
          if [ $? -eq 0 ]; then
            echo "### Docker Image Details" >> output.md
            echo "" >> output.md
            echo "To pull the image, use the following command:" >> output.md
            echo "\`\`\`" >> output.md
            echo "docker pull consensys/linea-besu-package:${{ steps.assemble.outputs.dockertag }}" >> output.md
            echo "\`\`\`" >> output.md
            if [[ "${{ inputs.with_besu_fleet_plugin }}" == "true" ]]; then
              echo "To pull the image with Besu fleet plugin, use the following command:" >> output.md
              echo "\`\`\`" >> output.md
              echo "docker pull consensys/linea-besu-package-with-fleet:${{ steps.assemble.outputs.dockertag }}" >> output.md
              echo "\`\`\`" >> output.md
            fi
            echo "" >> output.md
            echo "| Digest | OS | Architecture |" >> output.md
            echo "|--------|----|--------------|" >> output.md
            echo "$MANIFEST" | jq -r '.manifests[] | select(.platform.architecture != "unknown" and .platform.os != "unknown") | "| \(.digest) | \(.platform.os) | \(.platform.architecture) |"' >> output.md
          else
            echo "Docker image consensys/linea-besu-package:${{ steps.assemble.outputs.dockertag }} does not exist on dockerhub"
            exit 1
          fi

      - name: Conventional Changelog Action
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: change_log
        uses: TriPSs/conventional-changelog-action@3c4970b6573374889b897403d2f1278c395ea0df #v5.4.0
        with:
          git-path: ./linea-besu-package/
          git-push: false
          output-file: "false"

      - name: Append Changelog Action to release note
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: append_change_log
        shell: bash
        run: |
          cd release
          echo "## What's Changed" >> output.md
          echo "${{ steps.change_log.outputs.clean_changelog }}" >> output.md
          echo "output.md=$(cat output.md)"

      - name: release - publish artifacts and release notes
        id: release_publish
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 #v2.3.2
        with:
          name: Linea Besu Package ${{ steps.assemble.outputs.releasetag }}
          tag_name: linea-besu-package-${{ steps.assemble.outputs.releasetag }}
          body_path: release/output.md
          prerelease: ${{  github.event_name != 'workflow_dispatch' }}
          generate_release_notes: false
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
          files: |
            release/linea-besu-package-${{ steps.assemble.outputs.dockertag }}.tar.gz
