name: Export Security Report to CSV
on: workflow_dispatch
jobs:
  data_gathering:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-small
    steps:
      - name: CSV export
        uses: advanced-security/ghas-to-csv@v2
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: ghas-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error
