name: traces-api-facade-testing

on:
  workflow_call:

  workflow_dispatch:
    inputs:
      coverage:
        description: To generate test report
        required: false
        type: boolean
        default: false

concurrency:
  group: traces-api-facade-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    runs-on: [self-hosted, ubuntu-20.04, X64, small]
    name: Traces api facade tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run tests with coverage
        uses: nick-fields/retry@v2
        if: ${{ inputs.coverage }}
        with:
          max_attempts: 2
          retry_on: error
          timeout_minutes: 20
          command: |
            ./gradlew -V traces-api-facade:app:buildNeeded jacocoRootReport
      - name: Run tests without coverage
        uses: nick-fields/retry@v2
        if: ${{ !inputs.coverage }}
        with:
          max_attempts: 2
          retry_on: error
          timeout_minutes: 20
          command: |
            ./gradlew -V traces-api-facade:app:buildNeeded
