permissions: read-all
name: Daily Tracer Blockchain Tests

on:
  schedule:
    - cron: 0 21 * * 1-5
  workflow_dispatch:
    inputs:
      test_filter:
        description: Filter tests to run (via Gradle)
        required: false
        type: string
        default: "BlockchainReferenceTest_*"
      failed_module:
        description: Specific module to filter from failed tests
        required: false
        type: string
      failed_constraint:
        description: Specific module constrain pair to filter from failed tests
        required: false
        type: string
      commit:
        description: Commit to download artifact from
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # We run blockchain tests coming from the execution spec tests
  blockchain-reference-tests-osaka:
    uses: ./.github/workflows/reusable-tracer-blockchain-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA
      test_filter: ${{ inputs.test_filter || 'BlockchainReferenceTest_*' }}
      failed_module: ${{ inputs.failed_module || '' }}
      failed_constraint: ${{ inputs.failed_constraint || '' }}
      commit: ${{ inputs.commit || '' }}
