permissions: read-all
name: Weekly Tracer Tests

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly-unit-tests-osaka:
    uses: ./.github/workflows/reusable-tracer-weekly-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA

  weekly-prc-call-tests-osaka:
    uses: ./.github/workflows/reusable-tracer-weekly-prc-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA

  weekly-replay-tests:
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: recursive

      - name: Setup Tracer Test Environment
        uses: ./.github/actions/setup-tracer-environment

      - name: Run Weekly Replay tests
        run: GOMAXPROCS=10 GOMEMLIMIT=20GiB ./gradlew :tracer:arithmetization:weeklyReplayTests
        env:
          JAVA_OPTS: -Dorg.gradle.daemon=false
          GOCORSET_FLAGS: -v --ansi-escapes=false --report --air
          JUNIT_TESTS_PARALLELISM: 2

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: weekly-replay-tests-report
          path: tracer/arithmetization/build/reports/tests/**/*

  notify:
    needs: [ weekly-unit-tests-osaka, weekly-prc-call-tests-osaka, weekly-replay-tests ]
    if: ${{ always() && github.ref == 'refs/heads/main' && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    uses: ./.github/workflows/slack-notify-failed-jobs.yml
    with:
      title: "Weekly Tracer Tests workflow Failed"
      run_id: ${{ github.run_id }}
    secrets:
      channel_id: ${{ secrets.SLACK_ARITHMETIZATION_ALERTS_CHANNEL_ID }}
      slack_bot_token: ${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_BOT_TOKEN }}
