permissions: read-all
name: Daily Tracer Blockchain Tests

on:
  schedule:
    - cron: 0 21 * * 1-5
  workflow_dispatch:
    inputs:
      test_filter:
        description: Filter tests to run (via Gradle)
        required: false
        type: string
        default: "BlockchainReferenceTest_*"
      failed_module:
        description: Specific module to filter from failed tests
        required: false
        type: string
      failed_constraint:
        description: Specific module constrain pair to filter from failed tests
        required: false
        type: string
      commit:
        description: Commit to download artifact from
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # We run blockchain tests coming from the execution spec tests
  blockchain-reference-tests-osaka:
    uses: ./.github/workflows/reusable-tracer-blockchain-tests.yml
    secrets: inherit
    with:
      zkevm_fork: OSAKA
      test_filter: ${{ inputs.test_filter || 'BlockchainReferenceTest_*' }}
      failed_module: ${{ inputs.failed_module || '' }}
      failed_constraint: ${{ inputs.failed_constraint || '' }}
      commit: ${{ inputs.commit || '' }}

  notify:
    needs: [ blockchain-reference-tests-osaka ]
    if: ${{ always() && github.ref == 'refs/heads/main' && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
    uses: ./.github/workflows/slack-notify-failed-jobs.yml
    with:
      title: "Daily Tracer Blockchain Tests workflow Failed"
      run_id: ${{ github.run_id }}
      extra_message: "${{ needs.blockchain-reference-tests-osaka.outputs.success }} successful, ${{ needs.blockchain-reference-tests-osaka.outputs.failed }} failed, ${{ needs.blockchain-reference-tests-osaka.outputs.aborted }} aborted, ${{ needs.blockchain-reference-tests-osaka.outputs.disabled }} disabled"
    secrets:
      channel_id: ${{ secrets.SLACK_ARITHMETIZATION_ALERTS_CHANNEL_ID }}
      slack_bot_token: ${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_BOT_TOKEN }}
