name: transaction-exclusion-api-testing

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false
  workflow_dispatch:
    inputs:
      coverage:
        description: To generate test report
        required: false
        type: boolean
        default: false

concurrency:
  group: transaction-exclusion-api-testing-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    # ~1.5 mins saved vs small
    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-med
    name: Transaction exclusion api tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java and Gradle
        uses: ./.github/actions/setup-java-and-gradle
        with:
          distribution: temurin
          java-version: 21
      - name: Run tests with coverage
        if: ${{ inputs.coverage }}
        run: |
          ./gradlew transaction-exclusion-api:app:buildNeeded jacocoRootReport
      - name: Run tests without coverage
        if: ${{ !inputs.coverage }}
        run: |
          ./gradlew transaction-exclusion-api:app:buildNeeded
      - name: Login to Docker Hub
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 #v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run integration tests
        run: |
          ./gradlew transaction-exclusion-api:app:integrationTestAllNeeded
      - name: Upload Jacoco execution data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-transaction-exclusion-api-exec
          path: |
            **/build/jacoco/*.exec
          if-no-files-found: ignore
